#!/bin/bash
# This is a dummy script
# that does nothing real

ls -l

	# yeah
	# cool

#!/mechant
cat some-file   # shows instructions
echo "Yop#LaBoum"
echo "Super # Cool"

#
# Here is some other part
#

#rm -rf
norm -rf

